// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: podc/types/setting_steering_member.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	crypto "github.com/reapchain/reapchain-core/proto/podc/crypto"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SettingSteeringMember struct {
	Height                  int64            `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp               time.Time        `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	CoordinatorPubKey       crypto.PublicKey `protobuf:"bytes,3,opt,name=coordinator_pub_key,json=coordinatorPubKey,proto3" json:"coordinator_pub_key"`
	SteeringMemberAddresses [][]byte         `protobuf:"bytes,4,rep,name=steering_member_addresses,json=steeringMemberAddresses,proto3" json:"steering_member_addresses,omitempty"`
	Signature               []byte           `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SettingSteeringMember) Reset()         { *m = SettingSteeringMember{} }
func (m *SettingSteeringMember) String() string { return proto.CompactTextString(m) }
func (*SettingSteeringMember) ProtoMessage()    {}
func (*SettingSteeringMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_8409261c9cf211aa, []int{0}
}
func (m *SettingSteeringMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettingSteeringMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SettingSteeringMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SettingSteeringMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingSteeringMember.Merge(m, src)
}
func (m *SettingSteeringMember) XXX_Size() int {
	return m.Size()
}
func (m *SettingSteeringMember) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingSteeringMember.DiscardUnknown(m)
}

var xxx_messageInfo_SettingSteeringMember proto.InternalMessageInfo

func (m *SettingSteeringMember) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SettingSteeringMember) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *SettingSteeringMember) GetCoordinatorPubKey() crypto.PublicKey {
	if m != nil {
		return m.CoordinatorPubKey
	}
	return crypto.PublicKey{}
}

func (m *SettingSteeringMember) GetSteeringMemberAddresses() [][]byte {
	if m != nil {
		return m.SteeringMemberAddresses
	}
	return nil
}

func (m *SettingSteeringMember) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SettingSteeringMember)(nil), "reapchain.types.SettingSteeringMember")
}

func init() {
	proto.RegisterFile("podc/types/setting_steering_member.proto", fileDescriptor_8409261c9cf211aa)
}

var fileDescriptor_8409261c9cf211aa = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xbd, 0x6e, 0xdb, 0x30,
	0x10, 0x16, 0x6d, 0xd7, 0xa8, 0x55, 0x03, 0x45, 0xd5, 0xd6, 0x55, 0xdd, 0x42, 0x16, 0x32, 0x69,
	0x09, 0x09, 0x24, 0x99, 0xb2, 0x45, 0xab, 0x91, 0xc0, 0x91, 0x33, 0x65, 0x11, 0xf4, 0x73, 0xa1,
	0x08, 0x5b, 0xa2, 0x40, 0x52, 0x83, 0xde, 0xc2, 0x8f, 0x90, 0xc7, 0xf1, 0xe8, 0x31, 0x53, 0x12,
	0xd8, 0x2f, 0x12, 0x58, 0x92, 0xad, 0x24, 0xdb, 0xf1, 0xee, 0xbb, 0xef, 0xe7, 0xa8, 0x3b, 0x39,
	0x8f, 0x23, 0xa2, 0xca, 0x1c, 0x24, 0x91, 0xa0, 0x14, 0xcb, 0xa8, 0x2f, 0x15, 0x80, 0xd8, 0x17,
	0x29, 0xa4, 0x21, 0x08, 0x9c, 0x0b, 0xae, 0xb8, 0xf1, 0x5d, 0x40, 0x90, 0x47, 0x49, 0xc0, 0x32,
	0x5c, 0xc1, 0xc7, 0xbf, 0x28, 0xa7, 0xbc, 0x9a, 0x91, 0x7d, 0x55, 0xc3, 0xc6, 0xa3, 0x8a, 0x30,
	0x12, 0x65, 0xae, 0x38, 0x59, 0x40, 0x29, 0x9b, 0xfe, 0x84, 0x72, 0x4e, 0x97, 0x40, 0xaa, 0x57,
	0x58, 0x3c, 0x10, 0xc5, 0x52, 0x90, 0x2a, 0x48, 0xf3, 0x1a, 0x70, 0xf2, 0xd8, 0xd1, 0x7f, 0xcf,
	0x6b, 0x07, 0xf3, 0xc6, 0xc0, 0x75, 0xa5, 0x6f, 0x8c, 0xf4, 0x7e, 0x02, 0x8c, 0x26, 0xca, 0x44,
	0x36, 0x72, 0xba, 0x5e, 0xf3, 0x32, 0x5c, 0x7d, 0x70, 0x24, 0x31, 0x3b, 0x36, 0x72, 0xbe, 0x9d,
	0x8d, 0x71, 0x2d, 0x83, 0x0f, 0x32, 0xf8, 0xee, 0x80, 0x70, 0xbf, 0xae, 0x9f, 0x27, 0xda, 0xea,
	0x65, 0x82, 0xbc, 0x76, 0xcd, 0xb8, 0xd5, 0x7f, 0x46, 0x9c, 0x8b, 0x98, 0x65, 0x81, 0xe2, 0xc2,
	0xcf, 0x8b, 0xd0, 0x5f, 0x40, 0x69, 0x76, 0x2b, 0xb6, 0x7f, 0xb8, 0xcd, 0x5c, 0x27, 0xc2, 0xb3,
	0x22, 0x5c, 0xb2, 0x68, 0x0a, 0xa5, 0xdb, 0xdb, 0xd3, 0x79, 0x3f, 0xde, 0x6d, 0xcf, 0x8a, 0x70,
	0x0a, 0xa5, 0x71, 0xa9, 0xff, 0xfd, 0x74, 0x41, 0x3f, 0x88, 0x63, 0x01, 0x52, 0x82, 0x34, 0x7b,
	0x76, 0xd7, 0x19, 0x7a, 0x7f, 0xe4, 0x87, 0x84, 0x57, 0x87, 0xb1, 0xf1, 0x5f, 0x1f, 0x48, 0x46,
	0xb3, 0x40, 0x15, 0x02, 0xcc, 0x2f, 0x36, 0x72, 0x86, 0x5e, 0xdb, 0x70, 0x6f, 0xd6, 0x5b, 0x0b,
	0x6d, 0xb6, 0x16, 0x7a, 0xdd, 0x5a, 0x68, 0xb5, 0xb3, 0xb4, 0xcd, 0xce, 0xd2, 0x9e, 0x76, 0x96,
	0x76, 0x7f, 0x41, 0x99, 0x4a, 0x8a, 0x10, 0x47, 0x3c, 0x25, 0x47, 0xcf, 0x6d, 0x75, 0x1a, 0x71,
	0xd1, 0x9c, 0x9e, 0xb4, 0x1f, 0x1e, 0xf6, 0xab, 0xce, 0xf9, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0xc0, 0xbe, 0x8a, 0x05, 0x02, 0x00, 0x00,
}

func (m *SettingSteeringMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettingSteeringMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettingSteeringMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintSettingSteeringMember(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SteeringMemberAddresses) > 0 {
		for iNdEx := len(m.SteeringMemberAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SteeringMemberAddresses[iNdEx])
			copy(dAtA[i:], m.SteeringMemberAddresses[iNdEx])
			i = encodeVarintSettingSteeringMember(dAtA, i, uint64(len(m.SteeringMemberAddresses[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.CoordinatorPubKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSettingSteeringMember(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintSettingSteeringMember(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if m.Height != 0 {
		i = encodeVarintSettingSteeringMember(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSettingSteeringMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovSettingSteeringMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SettingSteeringMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovSettingSteeringMember(uint64(m.Height))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovSettingSteeringMember(uint64(l))
	l = m.CoordinatorPubKey.Size()
	n += 1 + l + sovSettingSteeringMember(uint64(l))
	if len(m.SteeringMemberAddresses) > 0 {
		for _, b := range m.SteeringMemberAddresses {
			l = len(b)
			n += 1 + l + sovSettingSteeringMember(uint64(l))
		}
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovSettingSteeringMember(uint64(l))
	}
	return n
}

func sovSettingSteeringMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSettingSteeringMember(x uint64) (n int) {
	return sovSettingSteeringMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SettingSteeringMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSettingSteeringMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettingSteeringMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettingSteeringMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatorPubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoordinatorPubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteeringMemberAddresses", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteeringMemberAddresses = append(m.SteeringMemberAddresses, make([]byte, postIndex-iNdEx))
			copy(m.SteeringMemberAddresses[len(m.SteeringMemberAddresses)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSettingSteeringMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSettingSteeringMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSettingSteeringMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSettingSteeringMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSettingSteeringMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSettingSteeringMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSettingSteeringMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSettingSteeringMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSettingSteeringMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSettingSteeringMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSettingSteeringMember = fmt.Errorf("proto: unexpected end of group")
)
