version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 0
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 0
    reviewers:
      - fadeev
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 0
    reviewers:
      - melekes
      - tessr
    labels:
      - T:dependencies
