// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reapchain/types/standing_member.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	crypto "github.com/reapchain/reapchain-core/proto/reapchain/crypto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StandingMemberSet struct {
	StandingMembers []*StandingMember `protobuf:"bytes,1,rep,name=standing_members,json=standingMembers,proto3" json:"standing_members,omitempty"`
	Coordinator     *StandingMember   `protobuf:"bytes,2,opt,name=coordinator,proto3" json:"coordinator,omitempty"`
}

func (m *StandingMemberSet) Reset()         { *m = StandingMemberSet{} }
func (m *StandingMemberSet) String() string { return proto.CompactTextString(m) }
func (*StandingMemberSet) ProtoMessage()    {}
func (*StandingMemberSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a88d847a7ccb362, []int{0}
}
func (m *StandingMemberSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StandingMemberSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StandingMemberSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StandingMemberSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandingMemberSet.Merge(m, src)
}
func (m *StandingMemberSet) XXX_Size() int {
	return m.Size()
}
func (m *StandingMemberSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StandingMemberSet.DiscardUnknown(m)
}

var xxx_messageInfo_StandingMemberSet proto.InternalMessageInfo

func (m *StandingMemberSet) GetStandingMembers() []*StandingMember {
	if m != nil {
		return m.StandingMembers
	}
	return nil
}

func (m *StandingMemberSet) GetCoordinator() *StandingMember {
	if m != nil {
		return m.Coordinator
	}
	return nil
}

type StandingMember struct {
	Address []byte           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey  crypto.PublicKey `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
}

func (m *StandingMember) Reset()         { *m = StandingMember{} }
func (m *StandingMember) String() string { return proto.CompactTextString(m) }
func (*StandingMember) ProtoMessage()    {}
func (*StandingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a88d847a7ccb362, []int{1}
}
func (m *StandingMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StandingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StandingMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StandingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandingMember.Merge(m, src)
}
func (m *StandingMember) XXX_Size() int {
	return m.Size()
}
func (m *StandingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_StandingMember.DiscardUnknown(m)
}

var xxx_messageInfo_StandingMember proto.InternalMessageInfo

func (m *StandingMember) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StandingMember) GetPubKey() crypto.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return crypto.PublicKey{}
}

type SimpleStandingMember struct {
	PubKey *crypto.PublicKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *SimpleStandingMember) Reset()         { *m = SimpleStandingMember{} }
func (m *SimpleStandingMember) String() string { return proto.CompactTextString(m) }
func (*SimpleStandingMember) ProtoMessage()    {}
func (*SimpleStandingMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a88d847a7ccb362, []int{2}
}
func (m *SimpleStandingMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimpleStandingMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimpleStandingMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimpleStandingMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStandingMember.Merge(m, src)
}
func (m *SimpleStandingMember) XXX_Size() int {
	return m.Size()
}
func (m *SimpleStandingMember) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStandingMember.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStandingMember proto.InternalMessageInfo

func (m *SimpleStandingMember) GetPubKey() *crypto.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*StandingMemberSet)(nil), "reapchain.types.StandingMemberSet")
	proto.RegisterType((*StandingMember)(nil), "reapchain.types.StandingMember")
	proto.RegisterType((*SimpleStandingMember)(nil), "reapchain.types.SimpleStandingMember")
}

func init() {
	proto.RegisterFile("reapchain/types/standing_member.proto", fileDescriptor_3a88d847a7ccb362)
}

var fileDescriptor_3a88d847a7ccb362 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x4a, 0x4d, 0x2c,
	0x48, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2f, 0x2e, 0x49, 0xcc,
	0x4b, 0xc9, 0xcc, 0x4b, 0x8f, 0xcf, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x87, 0x2b, 0xd3, 0x03, 0x2b, 0x93, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0xcb,
	0xe9, 0x83, 0x58, 0x10, 0x65, 0x52, 0xd2, 0x08, 0xd3, 0x92, 0x8b, 0x2a, 0x0b, 0x4a, 0xf2, 0xf5,
	0xb3, 0x53, 0x2b, 0x8b, 0x21, 0x92, 0x4a, 0x8b, 0x18, 0xb9, 0x04, 0x83, 0xa1, 0xa6, 0xfb, 0x82,
	0x0d, 0x0f, 0x4e, 0x2d, 0x11, 0xf2, 0xe2, 0x12, 0x40, 0xb3, 0xb2, 0x58, 0x82, 0x51, 0x81, 0x59,
	0x83, 0xdb, 0x48, 0x5e, 0x0f, 0xcd, 0x52, 0x3d, 0x54, 0xdd, 0x41, 0xfc, 0xc5, 0x28, 0xfc, 0x62,
	0x21, 0x47, 0x2e, 0xee, 0xe4, 0xfc, 0xfc, 0xa2, 0x94, 0xcc, 0xbc, 0xc4, 0x92, 0xfc, 0x22, 0x09,
	0x26, 0x05, 0x46, 0x62, 0x8c, 0x41, 0xd6, 0xa3, 0x94, 0xc6, 0xc5, 0x87, 0x2a, 0x2d, 0x24, 0xc1,
	0xc5, 0x9e, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x0c, 0x72, 0x17, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0x2b,
	0x64, 0xc5, 0xc5, 0x5e, 0x50, 0x9a, 0x14, 0x9f, 0x9d, 0x5a, 0x09, 0xb5, 0x4a, 0x1a, 0xc9, 0x2a,
	0x88, 0xff, 0xf5, 0x02, 0x4a, 0x93, 0x72, 0x32, 0x93, 0xbd, 0x53, 0x2b, 0x9d, 0x58, 0x4e, 0xdc,
	0x93, 0x67, 0x08, 0x62, 0x2b, 0x28, 0x4d, 0xf2, 0x4e, 0xad, 0x54, 0xf2, 0xe1, 0x12, 0x09, 0xce,
	0xcc, 0x2d, 0xc8, 0x49, 0x45, 0xb3, 0xcd, 0x04, 0x61, 0x26, 0x23, 0x41, 0x33, 0x61, 0xa6, 0x39,
	0x05, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e,
	0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x65, 0x7a, 0x66, 0x49,
	0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x22, 0x72, 0xe0, 0x2c, 0xdd, 0xe4, 0xfc, 0xa2,
	0x54, 0x7d, 0x48, 0x3c, 0xa2, 0xa5, 0x84, 0x24, 0x36, 0xb0, 0xb0, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x79, 0x70, 0xb6, 0x04, 0x23, 0x02, 0x00, 0x00,
}

func (m *StandingMemberSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StandingMemberSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StandingMemberSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Coordinator != nil {
		{
			size, err := m.Coordinator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStandingMember(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StandingMembers) > 0 {
		for iNdEx := len(m.StandingMembers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StandingMembers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStandingMember(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StandingMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StandingMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StandingMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStandingMember(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStandingMember(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SimpleStandingMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimpleStandingMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimpleStandingMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PubKey != nil {
		{
			size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStandingMember(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStandingMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovStandingMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StandingMemberSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StandingMembers) > 0 {
		for _, e := range m.StandingMembers {
			l = e.Size()
			n += 1 + l + sovStandingMember(uint64(l))
		}
	}
	if m.Coordinator != nil {
		l = m.Coordinator.Size()
		n += 1 + l + sovStandingMember(uint64(l))
	}
	return n
}

func (m *StandingMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStandingMember(uint64(l))
	}
	l = m.PubKey.Size()
	n += 1 + l + sovStandingMember(uint64(l))
	return n
}

func (m *SimpleStandingMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PubKey != nil {
		l = m.PubKey.Size()
		n += 1 + l + sovStandingMember(uint64(l))
	}
	return n
}

func sovStandingMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStandingMember(x uint64) (n int) {
	return sovStandingMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StandingMemberSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStandingMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StandingMemberSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StandingMemberSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StandingMembers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStandingMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStandingMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StandingMembers = append(m.StandingMembers, &StandingMember{})
			if err := m.StandingMembers[len(m.StandingMembers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coordinator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStandingMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStandingMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Coordinator == nil {
				m.Coordinator = &StandingMember{}
			}
			if err := m.Coordinator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStandingMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStandingMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StandingMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStandingMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StandingMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StandingMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStandingMember
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStandingMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStandingMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStandingMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStandingMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStandingMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimpleStandingMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStandingMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimpleStandingMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimpleStandingMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStandingMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStandingMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKey == nil {
				m.PubKey = &crypto.PublicKey{}
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStandingMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStandingMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStandingMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStandingMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStandingMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStandingMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStandingMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStandingMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStandingMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStandingMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStandingMember = fmt.Errorf("proto: unexpected end of group")
)
