---
apiVersion: v1
kind: Pod
metadata:
  name: transacter
spec:
  containers:
    - name: transacter
      image: reapchain-core/transacter
      command:
      - bash
      - "-c"
      - |
        set -ex
        while true
        do
          ./transact 100 "tm-0.dummy:26657"
          sleep 1
        done
