// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reapchain-core/types/vrf.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	crypto "github.com/reapchain/reapchain-core/proto/reapchain-core/crypto"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VrfSet struct {
	Height                     int64                       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Vrfs                       []*Vrf                      `protobuf:"bytes,2,rep,name=vrfs,proto3" json:"vrfs,omitempty"`
	SteeringMemberCandidateSet *SteeringMemberCandidateSet `protobuf:"bytes,3,opt,name=steering_member_candidate_set,json=steeringMemberCandidateSet,proto3" json:"steering_member_candidate_set,omitempty"`
}

func (m *VrfSet) Reset()         { *m = VrfSet{} }
func (m *VrfSet) String() string { return proto.CompactTextString(m) }
func (*VrfSet) ProtoMessage()    {}
func (*VrfSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e62ce2aaf2537f24, []int{0}
}
func (m *VrfSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VrfSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VrfSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VrfSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrfSet.Merge(m, src)
}
func (m *VrfSet) XXX_Size() int {
	return m.Size()
}
func (m *VrfSet) XXX_DiscardUnknown() {
	xxx_messageInfo_VrfSet.DiscardUnknown(m)
}

var xxx_messageInfo_VrfSet proto.InternalMessageInfo

func (m *VrfSet) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VrfSet) GetVrfs() []*Vrf {
	if m != nil {
		return m.Vrfs
	}
	return nil
}

func (m *VrfSet) GetSteeringMemberCandidateSet() *SteeringMemberCandidateSet {
	if m != nil {
		return m.SteeringMemberCandidateSet
	}
	return nil
}

type Vrf struct {
	Height                        int64            `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp                     time.Time        `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	SteeringMemberCandidatePubKey crypto.PublicKey `protobuf:"bytes,3,opt,name=steering_member_candidate_pub_key,json=steeringMemberCandidatePubKey,proto3" json:"steering_member_candidate_pub_key"`
	Value                         []byte           `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Proof                         []byte           `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	SteeringMemberCandidateIndex  int32            `protobuf:"varint,6,opt,name=steering_member_candidate_index,json=steeringMemberCandidateIndex,proto3" json:"steering_member_candidate_index,omitempty"`
	Seed                          []byte           `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (m *Vrf) Reset()         { *m = Vrf{} }
func (m *Vrf) String() string { return proto.CompactTextString(m) }
func (*Vrf) ProtoMessage()    {}
func (*Vrf) Descriptor() ([]byte, []int) {
	return fileDescriptor_e62ce2aaf2537f24, []int{1}
}
func (m *Vrf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vrf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vrf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vrf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vrf.Merge(m, src)
}
func (m *Vrf) XXX_Size() int {
	return m.Size()
}
func (m *Vrf) XXX_DiscardUnknown() {
	xxx_messageInfo_Vrf.DiscardUnknown(m)
}

var xxx_messageInfo_Vrf proto.InternalMessageInfo

func (m *Vrf) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Vrf) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *Vrf) GetSteeringMemberCandidatePubKey() crypto.PublicKey {
	if m != nil {
		return m.SteeringMemberCandidatePubKey
	}
	return crypto.PublicKey{}
}

func (m *Vrf) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Vrf) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *Vrf) GetSteeringMemberCandidateIndex() int32 {
	if m != nil {
		return m.SteeringMemberCandidateIndex
	}
	return 0
}

func (m *Vrf) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func init() {
	proto.RegisterType((*VrfSet)(nil), "reapchain.types.VrfSet")
	proto.RegisterType((*Vrf)(nil), "reapchain.types.Vrf")
}

func init() { proto.RegisterFile("reapchain-core/types/vrf.proto", fileDescriptor_e62ce2aaf2537f24) }

var fileDescriptor_e62ce2aaf2537f24 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xef, 0xf4, 0x9f, 0x3a, 0x2b, 0x08, 0x43, 0x91, 0xa1, 0xba, 0x69, 0xdc, 0x53, 0x40, 0x9c,
	0x81, 0xd5, 0xb3, 0x87, 0x8a, 0x07, 0x59, 0x84, 0x25, 0x95, 0x22, 0x5e, 0x4a, 0x92, 0xbe, 0xa4,
	0x43, 0x9b, 0x4c, 0x98, 0x99, 0x14, 0xf3, 0x2d, 0xf6, 0xf3, 0xf8, 0x09, 0xf6, 0xb8, 0x17, 0xc1,
	0x93, 0x4a, 0xfb, 0x45, 0x24, 0x93, 0xb4, 0x4a, 0xdd, 0xdc, 0xe6, 0xbd, 0xdf, 0xef, 0xf7, 0xde,
	0xfb, 0xbd, 0x79, 0xd8, 0x51, 0x10, 0xe4, 0xd1, 0x2a, 0x10, 0xd9, 0xab, 0x48, 0x2a, 0xe0, 0xa6,
	0xcc, 0x41, 0xf3, 0xad, 0x8a, 0x59, 0xae, 0xa4, 0x91, 0xe4, 0xc9, 0x11, 0x67, 0x16, 0x1a, 0x8f,
	0x12, 0x99, 0x48, 0x8b, 0xf1, 0xea, 0x55, 0xd3, 0xc6, 0xee, 0x49, 0x99, 0x48, 0x95, 0xb9, 0x91,
	0x7c, 0x0d, 0xa5, 0x6e, 0x18, 0x93, 0x44, 0xca, 0x64, 0x03, 0xdc, 0x46, 0x61, 0x11, 0x73, 0x23,
	0x52, 0xd0, 0x26, 0x48, 0xf3, 0x86, 0xf0, 0xe6, 0xde, 0x49, 0xb4, 0x01, 0x50, 0x22, 0x4b, 0x16,
	0x29, 0xa4, 0x21, 0xa8, 0x45, 0x14, 0x64, 0x4b, 0xb1, 0x0c, 0x0c, 0xd4, 0xaa, 0x8b, 0x6f, 0x08,
	0x0f, 0xe7, 0x2a, 0x9e, 0x81, 0x21, 0x4f, 0xf1, 0x70, 0x05, 0x22, 0x59, 0x19, 0x8a, 0x5c, 0xe4,
	0xf5, 0xfc, 0x26, 0x22, 0x1e, 0xee, 0x6f, 0x55, 0xac, 0x69, 0xd7, 0xed, 0x79, 0x67, 0x97, 0x23,
	0x76, 0xe2, 0x88, 0xcd, 0x55, 0xec, 0x5b, 0x06, 0xc9, 0xf0, 0x79, 0x6b, 0xbf, 0x85, 0x06, 0x43,
	0x7b, 0x2e, 0xf2, 0xce, 0x2e, 0x5f, 0xfe, 0x57, 0x62, 0xd6, 0xa8, 0x3e, 0x5a, 0xd1, 0xbb, 0x83,
	0x66, 0x06, 0xc6, 0x1f, 0xeb, 0x56, 0xec, 0xe2, 0x7b, 0x17, 0xf7, 0xe6, 0x2a, 0x6e, 0x9d, 0x7c,
	0x8a, 0x1f, 0x1d, 0xb7, 0x44, 0xbb, 0xb6, 0xf7, 0x98, 0xd5, 0x7b, 0x64, 0x87, 0x3d, 0xb2, 0x4f,
	0x07, 0xc6, 0xf4, 0xe1, 0xed, 0xcf, 0x49, 0xe7, 0xe6, 0xd7, 0x04, 0xf9, 0x7f, 0x65, 0x64, 0x8d,
	0x5f, 0xb4, 0x7b, 0xca, 0x8b, 0x70, 0xb1, 0x86, 0xb2, 0xf1, 0xf5, 0xec, 0x1f, 0x5f, 0xf5, 0x07,
	0xb2, 0xeb, 0x22, 0xdc, 0x88, 0xe8, 0x0a, 0xca, 0x69, 0xbf, 0x2a, 0xee, 0x9f, 0xb7, 0xb8, 0xb9,
	0x2e, 0xc2, 0x2b, 0x28, 0xc9, 0x08, 0x0f, 0xb6, 0xc1, 0xa6, 0x00, 0xda, 0x77, 0x91, 0xf7, 0xd8,
	0xaf, 0x83, 0x2a, 0x9b, 0x2b, 0x29, 0x63, 0x3a, 0xa8, 0xb3, 0x36, 0x20, 0xef, 0xf1, 0xa4, 0x7d,
	0x30, 0x91, 0x2d, 0xe1, 0x2b, 0x1d, 0xba, 0xc8, 0x1b, 0xf8, 0xcf, 0x5b, 0x7a, 0x7e, 0xa8, 0x38,
	0x84, 0xe0, 0xbe, 0x06, 0x58, 0xd2, 0x07, 0xb6, 0xb6, 0x7d, 0x4f, 0x3f, 0xdf, 0xee, 0x1c, 0x74,
	0xb7, 0x73, 0xd0, 0xef, 0x9d, 0x83, 0x6e, 0xf6, 0x4e, 0xe7, 0x6e, 0xef, 0x74, 0x7e, 0xec, 0x9d,
	0xce, 0x97, 0xb7, 0x89, 0x30, 0xab, 0x22, 0x64, 0x91, 0x4c, 0xf9, 0xd1, 0x2c, 0x3f, 0xb9, 0xbc,
	0xfa, 0xba, 0xef, 0x3b, 0xc7, 0x70, 0x68, 0xb1, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0xc4, 0x5b, 0x3b, 0x37, 0x03, 0x00, 0x00,
}

func (m *VrfSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VrfSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VrfSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SteeringMemberCandidateSet != nil {
		{
			size, err := m.SteeringMemberCandidateSet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVrf(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Vrfs) > 0 {
		for iNdEx := len(m.Vrfs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vrfs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVrf(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Height != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Vrf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vrf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vrf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Seed) > 0 {
		i -= len(m.Seed)
		copy(dAtA[i:], m.Seed)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.Seed)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SteeringMemberCandidateIndex != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.SteeringMemberCandidateIndex))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.SteeringMemberCandidatePubKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVrf(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintVrf(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if m.Height != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVrf(dAtA []byte, offset int, v uint64) int {
	offset -= sovVrf(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VrfSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovVrf(uint64(m.Height))
	}
	if len(m.Vrfs) > 0 {
		for _, e := range m.Vrfs {
			l = e.Size()
			n += 1 + l + sovVrf(uint64(l))
		}
	}
	if m.SteeringMemberCandidateSet != nil {
		l = m.SteeringMemberCandidateSet.Size()
		n += 1 + l + sovVrf(uint64(l))
	}
	return n
}

func (m *Vrf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovVrf(uint64(m.Height))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovVrf(uint64(l))
	l = m.SteeringMemberCandidatePubKey.Size()
	n += 1 + l + sovVrf(uint64(l))
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	if m.SteeringMemberCandidateIndex != 0 {
		n += 1 + sovVrf(uint64(m.SteeringMemberCandidateIndex))
	}
	l = len(m.Seed)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	return n
}

func sovVrf(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVrf(x uint64) (n int) {
	return sovVrf(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VrfSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VrfSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VrfSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vrfs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vrfs = append(m.Vrfs, &Vrf{})
			if err := m.Vrfs[len(m.Vrfs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteeringMemberCandidateSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SteeringMemberCandidateSet == nil {
				m.SteeringMemberCandidateSet = &SteeringMemberCandidateSet{}
			}
			if err := m.SteeringMemberCandidateSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vrf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vrf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vrf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteeringMemberCandidatePubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SteeringMemberCandidatePubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteeringMemberCandidateIndex", wireType)
			}
			m.SteeringMemberCandidateIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SteeringMemberCandidateIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = append(m.Seed[:0], dAtA[iNdEx:postIndex]...)
			if m.Seed == nil {
				m.Seed = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVrf(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVrf
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVrf
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVrf
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVrf        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVrf          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVrf = fmt.Errorf("proto: unexpected end of group")
)
